package cn.zm.trip.web.dao;

import cn.zm.trip.web.domain.Station;
import cn.zm.trip.web.domain.StationExample;
import java.util.List;

public interface StationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tpSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    int insert(Station record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    int insertSelective(Station record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    List<Station> selectByExample(StationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    Station selectByPrimaryKey(Integer tpSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Station record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Station record);


    List<Station> stationPointSearch(Station record);
}