package cn.zm.trip.web.dao;

import cn.zm.trip.web.domain.User;
import cn.zm.trip.web.domain.UserExample;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserDao {

	/**
	 * 插入用户
	 * @param user
	 */
	void insertUser(User user);

	/**
	 * 查询所有用户
	 * @return
	 */
	List<User> selectAll();

	/**
	 * 查询用户名
	 * @return
	 */

	User selectbyname(String name);
	/**
	 * 查询用户邮箱
	 * @return
	 */
	User selectbyemail(String email);

	/**
	 * 用户模糊查询
	 * @param user
	 * @return
	 */
	List<User> search(User user);

	/**
	 * 单击删除用户
	 */
	void userDelete(String uid);

	/**
	 * 用户登录
	 *
	 */
	User userLogin(User user);

//	/**
//	 * 用户单个查询  垃圾 2021-1-7 13:00 ~ 17:51  yyy
//	 *
//	 */
//	User userGet(String uid);

	/**
	 * 用户信息更新
	 *
	 */
	void updataUserInfo(User user);

	/**
	 * 用户喜好更新
	 *
	 */
	void updataUserLike(String uid, String tp_like);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tp_user
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer tpUid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tp_user
	 *
	 * @mbg.generated
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tp_user
	 *
	 * @mbg.generated
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tp_user
	 *
	 * @mbg.generated
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tp_user
	 *
	 * @mbg.generated
	 */
	User selectByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tp_user
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tp_user
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(User record);
}
