package cn.zm.trip.web.domain;

import java.util.ArrayList;
import java.util.List;

public class CityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    public CityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTpCidIsNull() {
            addCriterion("tp_cid is null");
            return (Criteria) this;
        }

        public Criteria andTpCidIsNotNull() {
            addCriterion("tp_cid is not null");
            return (Criteria) this;
        }

        public Criteria andTpCidEqualTo(Integer value) {
            addCriterion("tp_cid =", value, "tpCid");
            return (Criteria) this;
        }

        public Criteria andTpCidNotEqualTo(Integer value) {
            addCriterion("tp_cid <>", value, "tpCid");
            return (Criteria) this;
        }

        public Criteria andTpCidGreaterThan(Integer value) {
            addCriterion("tp_cid >", value, "tpCid");
            return (Criteria) this;
        }

        public Criteria andTpCidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tp_cid >=", value, "tpCid");
            return (Criteria) this;
        }

        public Criteria andTpCidLessThan(Integer value) {
            addCriterion("tp_cid <", value, "tpCid");
            return (Criteria) this;
        }

        public Criteria andTpCidLessThanOrEqualTo(Integer value) {
            addCriterion("tp_cid <=", value, "tpCid");
            return (Criteria) this;
        }

        public Criteria andTpCidIn(List<Integer> values) {
            addCriterion("tp_cid in", values, "tpCid");
            return (Criteria) this;
        }

        public Criteria andTpCidNotIn(List<Integer> values) {
            addCriterion("tp_cid not in", values, "tpCid");
            return (Criteria) this;
        }

        public Criteria andTpCidBetween(Integer value1, Integer value2) {
            addCriterion("tp_cid between", value1, value2, "tpCid");
            return (Criteria) this;
        }

        public Criteria andTpCidNotBetween(Integer value1, Integer value2) {
            addCriterion("tp_cid not between", value1, value2, "tpCid");
            return (Criteria) this;
        }

        public Criteria andTpCnameIsNull() {
            addCriterion("tp_cname is null");
            return (Criteria) this;
        }

        public Criteria andTpCnameIsNotNull() {
            addCriterion("tp_cname is not null");
            return (Criteria) this;
        }

        public Criteria andTpCnameEqualTo(String value) {
            addCriterion("tp_cname =", value, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCnameNotEqualTo(String value) {
            addCriterion("tp_cname <>", value, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCnameGreaterThan(String value) {
            addCriterion("tp_cname >", value, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCnameGreaterThanOrEqualTo(String value) {
            addCriterion("tp_cname >=", value, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCnameLessThan(String value) {
            addCriterion("tp_cname <", value, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCnameLessThanOrEqualTo(String value) {
            addCriterion("tp_cname <=", value, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCnameLike(String value) {
            addCriterion("tp_cname like", value, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCnameNotLike(String value) {
            addCriterion("tp_cname not like", value, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCnameIn(List<String> values) {
            addCriterion("tp_cname in", values, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCnameNotIn(List<String> values) {
            addCriterion("tp_cname not in", values, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCnameBetween(String value1, String value2) {
            addCriterion("tp_cname between", value1, value2, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCnameNotBetween(String value1, String value2) {
            addCriterion("tp_cname not between", value1, value2, "tpCname");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceIsNull() {
            addCriterion("tp_cprovince is null");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceIsNotNull() {
            addCriterion("tp_cprovince is not null");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceEqualTo(String value) {
            addCriterion("tp_cprovince =", value, "tpCprovince");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceNotEqualTo(String value) {
            addCriterion("tp_cprovince <>", value, "tpCprovince");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceGreaterThan(String value) {
            addCriterion("tp_cprovince >", value, "tpCprovince");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceGreaterThanOrEqualTo(String value) {
            addCriterion("tp_cprovince >=", value, "tpCprovince");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceLessThan(String value) {
            addCriterion("tp_cprovince <", value, "tpCprovince");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceLessThanOrEqualTo(String value) {
            addCriterion("tp_cprovince <=", value, "tpCprovince");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceLike(String value) {
            addCriterion("tp_cprovince like", value, "tpCprovince");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceNotLike(String value) {
            addCriterion("tp_cprovince not like", value, "tpCprovince");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceIn(List<String> values) {
            addCriterion("tp_cprovince in", values, "tpCprovince");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceNotIn(List<String> values) {
            addCriterion("tp_cprovince not in", values, "tpCprovince");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceBetween(String value1, String value2) {
            addCriterion("tp_cprovince between", value1, value2, "tpCprovince");
            return (Criteria) this;
        }

        public Criteria andTpCprovinceNotBetween(String value1, String value2) {
            addCriterion("tp_cprovince not between", value1, value2, "tpCprovince");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_city
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_city
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}