package cn.zm.trip.web.domain;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_city.tp_cid
     *
     * @mbg.generated
     */
    private Integer tpCid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_city.tp_cname
     *
     * @mbg.generated
     */
    private String tpCname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_city.tp_cprovince
     *
     * @mbg.generated
     */
    private String tpCprovince;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_city.tp_cid
     *
     * @return the value of tp_city.tp_cid
     *
     * @mbg.generated
     */
    public Integer getTpCid() {
        return tpCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_city.tp_cid
     *
     * @param tpCid the value for tp_city.tp_cid
     *
     * @mbg.generated
     */
    public void setTpCid(Integer tpCid) {
        this.tpCid = tpCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_city.tp_cname
     *
     * @return the value of tp_city.tp_cname
     *
     * @mbg.generated
     */
    public String getTpCname() {
        return tpCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_city.tp_cname
     *
     * @param tpCname the value for tp_city.tp_cname
     *
     * @mbg.generated
     */
    public void setTpCname(String tpCname) {
        this.tpCname = tpCname == null ? null : tpCname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_city.tp_cprovince
     *
     * @return the value of tp_city.tp_cprovince
     *
     * @mbg.generated
     */
    public String getTpCprovince() {
        return tpCprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_city.tp_cprovince
     *
     * @param tpCprovince the value for tp_city.tp_cprovince
     *
     * @mbg.generated
     */
    public void setTpCprovince(String tpCprovince) {
        this.tpCprovince = tpCprovince == null ? null : tpCprovince.trim();
    }
}