package cn.zm.trip.web.domain;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.tp_oid
     *
     * @mbg.generated
     */
    private String tpOid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.tp_uid
     *
     * @mbg.generated
     */
    private Integer tpUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.tp_oinfo
     *
     * @mbg.generated
     */
    private String tpOinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_order.tp_status
     *
     * @mbg.generated
     */
    private String tpStatus;

    public Order(String tpOid, Integer tpUid, String tpOinfo, String tpStatus) {
        this.tpOid = tpOid;
        this.tpUid = tpUid;
        this.tpOinfo = tpOinfo;
        this.tpStatus = tpStatus;
    }

    public Order(){}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.tp_oid
     *
     * @return the value of tp_order.tp_oid
     *
     * @mbg.generated
     */
    public String getTpOid() {
        return tpOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.tp_oid
     *
     * @param tpOid the value for tp_order.tp_oid
     *
     * @mbg.generated
     */
    public void setTpOid(String tpOid) {
        this.tpOid = tpOid == null ? null : tpOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.tp_uid
     *
     * @return the value of tp_order.tp_uid
     *
     * @mbg.generated
     */
    public Integer getTpUid() {
        return tpUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.tp_uid
     *
     * @param tpUid the value for tp_order.tp_uid
     *
     * @mbg.generated
     */
    public void setTpUid(Integer tpUid) {
        this.tpUid = tpUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.tp_oinfo
     *
     * @return the value of tp_order.tp_oinfo
     *
     * @mbg.generated
     */
    public String getTpOinfo() {
        return tpOinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.tp_oinfo
     *
     * @param tpOinfo the value for tp_order.tp_oinfo
     *
     * @mbg.generated
     */
    public void setTpOinfo(String tpOinfo) {
        this.tpOinfo = tpOinfo == null ? null : tpOinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_order.tp_status
     *
     * @return the value of tp_order.tp_status
     *
     * @mbg.generated
     */
    public String getTpStatus() {
        return tpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_order.tp_status
     *
     * @param tpStatus the value for tp_order.tp_status
     *
     * @mbg.generated
     */
    public void setTpStatus(String tpStatus) {
        this.tpStatus = tpStatus == null ? null : tpStatus.trim();
    }
}