package cn.zm.trip.web.domain;

import java.util.ArrayList;
import java.util.List;

public class StationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    public StationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTpSidIsNull() {
            addCriterion("tp_sid is null");
            return (Criteria) this;
        }

        public Criteria andTpSidIsNotNull() {
            addCriterion("tp_sid is not null");
            return (Criteria) this;
        }

        public Criteria andTpSidEqualTo(Integer value) {
            addCriterion("tp_sid =", value, "tpSid");
            return (Criteria) this;
        }

        public Criteria andTpSidNotEqualTo(Integer value) {
            addCriterion("tp_sid <>", value, "tpSid");
            return (Criteria) this;
        }

        public Criteria andTpSidGreaterThan(Integer value) {
            addCriterion("tp_sid >", value, "tpSid");
            return (Criteria) this;
        }

        public Criteria andTpSidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tp_sid >=", value, "tpSid");
            return (Criteria) this;
        }

        public Criteria andTpSidLessThan(Integer value) {
            addCriterion("tp_sid <", value, "tpSid");
            return (Criteria) this;
        }

        public Criteria andTpSidLessThanOrEqualTo(Integer value) {
            addCriterion("tp_sid <=", value, "tpSid");
            return (Criteria) this;
        }

        public Criteria andTpSidIn(List<Integer> values) {
            addCriterion("tp_sid in", values, "tpSid");
            return (Criteria) this;
        }

        public Criteria andTpSidNotIn(List<Integer> values) {
            addCriterion("tp_sid not in", values, "tpSid");
            return (Criteria) this;
        }

        public Criteria andTpSidBetween(Integer value1, Integer value2) {
            addCriterion("tp_sid between", value1, value2, "tpSid");
            return (Criteria) this;
        }

        public Criteria andTpSidNotBetween(Integer value1, Integer value2) {
            addCriterion("tp_sid not between", value1, value2, "tpSid");
            return (Criteria) this;
        }

        public Criteria andTpSnameIsNull() {
            addCriterion("tp_sname is null");
            return (Criteria) this;
        }

        public Criteria andTpSnameIsNotNull() {
            addCriterion("tp_sname is not null");
            return (Criteria) this;
        }

        public Criteria andTpSnameEqualTo(String value) {
            addCriterion("tp_sname =", value, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpSnameNotEqualTo(String value) {
            addCriterion("tp_sname <>", value, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpSnameGreaterThan(String value) {
            addCriterion("tp_sname >", value, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpSnameGreaterThanOrEqualTo(String value) {
            addCriterion("tp_sname >=", value, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpSnameLessThan(String value) {
            addCriterion("tp_sname <", value, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpSnameLessThanOrEqualTo(String value) {
            addCriterion("tp_sname <=", value, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpSnameLike(String value) {
            addCriterion("tp_sname like", value, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpSnameNotLike(String value) {
            addCriterion("tp_sname not like", value, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpSnameIn(List<String> values) {
            addCriterion("tp_sname in", values, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpSnameNotIn(List<String> values) {
            addCriterion("tp_sname not in", values, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpSnameBetween(String value1, String value2) {
            addCriterion("tp_sname between", value1, value2, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpSnameNotBetween(String value1, String value2) {
            addCriterion("tp_sname not between", value1, value2, "tpSname");
            return (Criteria) this;
        }

        public Criteria andTpStypeIsNull() {
            addCriterion("tp_stype is null");
            return (Criteria) this;
        }

        public Criteria andTpStypeIsNotNull() {
            addCriterion("tp_stype is not null");
            return (Criteria) this;
        }

        public Criteria andTpStypeEqualTo(String value) {
            addCriterion("tp_stype =", value, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpStypeNotEqualTo(String value) {
            addCriterion("tp_stype <>", value, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpStypeGreaterThan(String value) {
            addCriterion("tp_stype >", value, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpStypeGreaterThanOrEqualTo(String value) {
            addCriterion("tp_stype >=", value, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpStypeLessThan(String value) {
            addCriterion("tp_stype <", value, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpStypeLessThanOrEqualTo(String value) {
            addCriterion("tp_stype <=", value, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpStypeLike(String value) {
            addCriterion("tp_stype like", value, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpStypeNotLike(String value) {
            addCriterion("tp_stype not like", value, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpStypeIn(List<String> values) {
            addCriterion("tp_stype in", values, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpStypeNotIn(List<String> values) {
            addCriterion("tp_stype not in", values, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpStypeBetween(String value1, String value2) {
            addCriterion("tp_stype between", value1, value2, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpStypeNotBetween(String value1, String value2) {
            addCriterion("tp_stype not between", value1, value2, "tpStype");
            return (Criteria) this;
        }

        public Criteria andTpSlocalIsNull() {
            addCriterion("tp_slocal is null");
            return (Criteria) this;
        }

        public Criteria andTpSlocalIsNotNull() {
            addCriterion("tp_slocal is not null");
            return (Criteria) this;
        }

        public Criteria andTpSlocalEqualTo(String value) {
            addCriterion("tp_slocal =", value, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlocalNotEqualTo(String value) {
            addCriterion("tp_slocal <>", value, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlocalGreaterThan(String value) {
            addCriterion("tp_slocal >", value, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlocalGreaterThanOrEqualTo(String value) {
            addCriterion("tp_slocal >=", value, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlocalLessThan(String value) {
            addCriterion("tp_slocal <", value, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlocalLessThanOrEqualTo(String value) {
            addCriterion("tp_slocal <=", value, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlocalLike(String value) {
            addCriterion("tp_slocal like", value, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlocalNotLike(String value) {
            addCriterion("tp_slocal not like", value, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlocalIn(List<String> values) {
            addCriterion("tp_slocal in", values, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlocalNotIn(List<String> values) {
            addCriterion("tp_slocal not in", values, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlocalBetween(String value1, String value2) {
            addCriterion("tp_slocal between", value1, value2, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlocalNotBetween(String value1, String value2) {
            addCriterion("tp_slocal not between", value1, value2, "tpSlocal");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeIsNull() {
            addCriterion("tp_slongitude is null");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeIsNotNull() {
            addCriterion("tp_slongitude is not null");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeEqualTo(String value) {
            addCriterion("tp_slongitude =", value, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeNotEqualTo(String value) {
            addCriterion("tp_slongitude <>", value, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeGreaterThan(String value) {
            addCriterion("tp_slongitude >", value, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("tp_slongitude >=", value, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeLessThan(String value) {
            addCriterion("tp_slongitude <", value, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeLessThanOrEqualTo(String value) {
            addCriterion("tp_slongitude <=", value, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeLike(String value) {
            addCriterion("tp_slongitude like", value, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeNotLike(String value) {
            addCriterion("tp_slongitude not like", value, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeIn(List<String> values) {
            addCriterion("tp_slongitude in", values, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeNotIn(List<String> values) {
            addCriterion("tp_slongitude not in", values, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeBetween(String value1, String value2) {
            addCriterion("tp_slongitude between", value1, value2, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlongitudeNotBetween(String value1, String value2) {
            addCriterion("tp_slongitude not between", value1, value2, "tpSlongitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeIsNull() {
            addCriterion("tp_slatitude is null");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeIsNotNull() {
            addCriterion("tp_slatitude is not null");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeEqualTo(String value) {
            addCriterion("tp_slatitude =", value, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeNotEqualTo(String value) {
            addCriterion("tp_slatitude <>", value, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeGreaterThan(String value) {
            addCriterion("tp_slatitude >", value, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("tp_slatitude >=", value, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeLessThan(String value) {
            addCriterion("tp_slatitude <", value, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeLessThanOrEqualTo(String value) {
            addCriterion("tp_slatitude <=", value, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeLike(String value) {
            addCriterion("tp_slatitude like", value, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeNotLike(String value) {
            addCriterion("tp_slatitude not like", value, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeIn(List<String> values) {
            addCriterion("tp_slatitude in", values, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeNotIn(List<String> values) {
            addCriterion("tp_slatitude not in", values, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeBetween(String value1, String value2) {
            addCriterion("tp_slatitude between", value1, value2, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpSlatitudeNotBetween(String value1, String value2) {
            addCriterion("tp_slatitude not between", value1, value2, "tpSlatitude");
            return (Criteria) this;
        }

        public Criteria andTpScityIsNull() {
            addCriterion("tp_scity is null");
            return (Criteria) this;
        }

        public Criteria andTpScityIsNotNull() {
            addCriterion("tp_scity is not null");
            return (Criteria) this;
        }

        public Criteria andTpScityEqualTo(String value) {
            addCriterion("tp_scity =", value, "tpScity");
            return (Criteria) this;
        }

        public Criteria andTpScityNotEqualTo(String value) {
            addCriterion("tp_scity <>", value, "tpScity");
            return (Criteria) this;
        }

        public Criteria andTpScityGreaterThan(String value) {
            addCriterion("tp_scity >", value, "tpScity");
            return (Criteria) this;
        }

        public Criteria andTpScityGreaterThanOrEqualTo(String value) {
            addCriterion("tp_scity >=", value, "tpScity");
            return (Criteria) this;
        }

        public Criteria andTpScityLessThan(String value) {
            addCriterion("tp_scity <", value, "tpScity");
            return (Criteria) this;
        }

        public Criteria andTpScityLessThanOrEqualTo(String value) {
            addCriterion("tp_scity <=", value, "tpScity");
            return (Criteria) this;
        }

        public Criteria andTpScityLike(String value) {
            addCriterion("tp_scity like", value, "tpScity");
            return (Criteria) this;
        }

        public Criteria andTpScityNotLike(String value) {
            addCriterion("tp_scity not like", value, "tpScity");
            return (Criteria) this;
        }

        public Criteria andTpScityIn(List<String> values) {
            addCriterion("tp_scity in", values, "tpScity");
            return (Criteria) this;
        }

        public Criteria andTpScityNotIn(List<String> values) {
            addCriterion("tp_scity not in", values, "tpScity");
            return (Criteria) this;
        }

        public Criteria andTpScityBetween(String value1, String value2) {
            addCriterion("tp_scity between", value1, value2, "tpScity");
            return (Criteria) this;
        }

        public Criteria andTpScityNotBetween(String value1, String value2) {
            addCriterion("tp_scity not between", value1, value2, "tpScity");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_station
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_station
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    @Override
    public boolean equals(Object obj) {
        return true;
    }
}