package cn.zm.trip.web.domain;

public class Station {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_station.tp_sid
     *
     * @mbg.generated
     */
    private Integer tpSid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_station.tp_sname
     *
     * @mbg.generated
     */
    private String tpSname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_station.tp_stype
     *
     * @mbg.generated
     */
    private String tpStype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_station.tp_slocal
     *
     * @mbg.generated
     */
    private String tpSlocal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_station.tp_slongitude
     *
     * @mbg.generated
     */
    private String tpSlongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_station.tp_slatitude
     *
     * @mbg.generated
     */
    private String tpSlatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_station.tp_scity
     *
     * @mbg.generated
     */
    private String tpScity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_station.tp_sid
     *
     * @return the value of tp_station.tp_sid
     *
     * @mbg.generated
     */
    public Integer getTpSid() {
        return tpSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_station.tp_sid
     *
     * @param tpSid the value for tp_station.tp_sid
     *
     * @mbg.generated
     */
    public void setTpSid(Integer tpSid) {
        this.tpSid = tpSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_station.tp_sname
     *
     * @return the value of tp_station.tp_sname
     *
     * @mbg.generated
     */
    public String getTpSname() {
        return tpSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_station.tp_sname
     *
     * @param tpSname the value for tp_station.tp_sname
     *
     * @mbg.generated
     */
    public void setTpSname(String tpSname) {
        this.tpSname = tpSname == null ? null : tpSname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_station.tp_stype
     *
     * @return the value of tp_station.tp_stype
     *
     * @mbg.generated
     */
    public String getTpStype() {
        return tpStype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_station.tp_stype
     *
     * @param tpStype the value for tp_station.tp_stype
     *
     * @mbg.generated
     */
    public void setTpStype(String tpStype) {
        this.tpStype = tpStype == null ? null : tpStype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_station.tp_slocal
     *
     * @return the value of tp_station.tp_slocal
     *
     * @mbg.generated
     */
    public String getTpSlocal() {
        return tpSlocal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_station.tp_slocal
     *
     * @param tpSlocal the value for tp_station.tp_slocal
     *
     * @mbg.generated
     */
    public void setTpSlocal(String tpSlocal) {
        this.tpSlocal = tpSlocal == null ? null : tpSlocal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_station.tp_slongitude
     *
     * @return the value of tp_station.tp_slongitude
     *
     * @mbg.generated
     */
    public String getTpSlongitude() {
        return tpSlongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_station.tp_slongitude
     *
     * @param tpSlongitude the value for tp_station.tp_slongitude
     *
     * @mbg.generated
     */
    public void setTpSlongitude(String tpSlongitude) {
        this.tpSlongitude = tpSlongitude == null ? null : tpSlongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_station.tp_slatitude
     *
     * @return the value of tp_station.tp_slatitude
     *
     * @mbg.generated
     */
    public String getTpSlatitude() {
        return tpSlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_station.tp_slatitude
     *
     * @param tpSlatitude the value for tp_station.tp_slatitude
     *
     * @mbg.generated
     */
    public void setTpSlatitude(String tpSlatitude) {
        this.tpSlatitude = tpSlatitude == null ? null : tpSlatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_station.tp_scity
     *
     * @return the value of tp_station.tp_scity
     *
     * @mbg.generated
     */
    public String getTpScity() {
        return tpScity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_station.tp_scity
     *
     * @param tpScity the value for tp_station.tp_scity
     *
     * @mbg.generated
     */
    public void setTpScity(String tpScity) {
        this.tpScity = tpScity == null ? null : tpScity.trim();
    }
}