package cn.zm.trip.web.domain;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Component
public class ViewPointExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    public ViewPointExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTpVidIsNull() {
            addCriterion("tp_vid is null");
            return (Criteria) this;
        }

        public Criteria andTpVidIsNotNull() {
            addCriterion("tp_vid is not null");
            return (Criteria) this;
        }

        public Criteria andTpVidEqualTo(Integer value) {
            addCriterion("tp_vid =", value, "tpVid");
            return (Criteria) this;
        }

        public Criteria andTpVidNotEqualTo(Integer value) {
            addCriterion("tp_vid <>", value, "tpVid");
            return (Criteria) this;
        }

        public Criteria andTpVidGreaterThan(Integer value) {
            addCriterion("tp_vid >", value, "tpVid");
            return (Criteria) this;
        }

        public Criteria andTpVidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tp_vid >=", value, "tpVid");
            return (Criteria) this;
        }

        public Criteria andTpVidLessThan(Integer value) {
            addCriterion("tp_vid <", value, "tpVid");
            return (Criteria) this;
        }

        public Criteria andTpVidLessThanOrEqualTo(Integer value) {
            addCriterion("tp_vid <=", value, "tpVid");
            return (Criteria) this;
        }

        public Criteria andTpVidIn(List<Integer> values) {
            addCriterion("tp_vid in", values, "tpVid");
            return (Criteria) this;
        }

        public Criteria andTpVidNotIn(List<Integer> values) {
            addCriterion("tp_vid not in", values, "tpVid");
            return (Criteria) this;
        }

        public Criteria andTpVidBetween(Integer value1, Integer value2) {
            addCriterion("tp_vid between", value1, value2, "tpVid");
            return (Criteria) this;
        }

        public Criteria andTpVidNotBetween(Integer value1, Integer value2) {
            addCriterion("tp_vid not between", value1, value2, "tpVid");
            return (Criteria) this;
        }

        public Criteria andTpTitleIsNull() {
            addCriterion("tp_title is null");
            return (Criteria) this;
        }

        public Criteria andTpTitleIsNotNull() {
            addCriterion("tp_title is not null");
            return (Criteria) this;
        }

        public Criteria andTpTitleEqualTo(String value) {
            addCriterion("tp_title =", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleNotEqualTo(String value) {
            addCriterion("tp_title <>", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleGreaterThan(String value) {
            addCriterion("tp_title >", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleGreaterThanOrEqualTo(String value) {
            addCriterion("tp_title >=", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleLessThan(String value) {
            addCriterion("tp_title <", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleLessThanOrEqualTo(String value) {
            addCriterion("tp_title <=", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleLike(String value) {
            addCriterion("tp_title like", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleNotLike(String value) {
            addCriterion("tp_title not like", value, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleIn(List<String> values) {
            addCriterion("tp_title in", values, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleNotIn(List<String> values) {
            addCriterion("tp_title not in", values, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleBetween(String value1, String value2) {
            addCriterion("tp_title between", value1, value2, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpTitleNotBetween(String value1, String value2) {
            addCriterion("tp_title not between", value1, value2, "tpTitle");
            return (Criteria) this;
        }

        public Criteria andTpVnameIsNull() {
            addCriterion("tp_vname is null");
            return (Criteria) this;
        }

        public Criteria andTpVnameIsNotNull() {
            addCriterion("tp_vname is not null");
            return (Criteria) this;
        }

        public Criteria andTpVnameEqualTo(String value) {
            addCriterion("tp_vname =", value, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVnameNotEqualTo(String value) {
            addCriterion("tp_vname <>", value, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVnameGreaterThan(String value) {
            addCriterion("tp_vname >", value, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVnameGreaterThanOrEqualTo(String value) {
            addCriterion("tp_vname >=", value, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVnameLessThan(String value) {
            addCriterion("tp_vname <", value, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVnameLessThanOrEqualTo(String value) {
            addCriterion("tp_vname <=", value, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVnameLike(String value) {
            addCriterion("tp_vname like", value, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVnameNotLike(String value) {
            addCriterion("tp_vname not like", value, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVnameIn(List<String> values) {
            addCriterion("tp_vname in", values, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVnameNotIn(List<String> values) {
            addCriterion("tp_vname not in", values, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVnameBetween(String value1, String value2) {
            addCriterion("tp_vname between", value1, value2, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVnameNotBetween(String value1, String value2) {
            addCriterion("tp_vname not between", value1, value2, "tpVname");
            return (Criteria) this;
        }

        public Criteria andTpVtypeIsNull() {
            addCriterion("tp_vtype is null");
            return (Criteria) this;
        }

        public Criteria andTpVtypeIsNotNull() {
            addCriterion("tp_vtype is not null");
            return (Criteria) this;
        }

        public Criteria andTpVtypeEqualTo(String value) {
            addCriterion("tp_vtype =", value, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVtypeNotEqualTo(String value) {
            addCriterion("tp_vtype <>", value, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVtypeGreaterThan(String value) {
            addCriterion("tp_vtype >", value, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVtypeGreaterThanOrEqualTo(String value) {
            addCriterion("tp_vtype >=", value, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVtypeLessThan(String value) {
            addCriterion("tp_vtype <", value, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVtypeLessThanOrEqualTo(String value) {
            addCriterion("tp_vtype <=", value, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVtypeLike(String value) {
            addCriterion("tp_vtype like", value, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVtypeNotLike(String value) {
            addCriterion("tp_vtype not like", value, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVtypeIn(List<String> values) {
            addCriterion("tp_vtype in", values, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVtypeNotIn(List<String> values) {
            addCriterion("tp_vtype not in", values, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVtypeBetween(String value1, String value2) {
            addCriterion("tp_vtype between", value1, value2, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVtypeNotBetween(String value1, String value2) {
            addCriterion("tp_vtype not between", value1, value2, "tpVtype");
            return (Criteria) this;
        }

        public Criteria andTpVpicIsNull() {
            addCriterion("tp_vpic is null");
            return (Criteria) this;
        }

        public Criteria andTpVpicIsNotNull() {
            addCriterion("tp_vpic is not null");
            return (Criteria) this;
        }

        public Criteria andTpVpicEqualTo(String value) {
            addCriterion("tp_vpic =", value, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVpicNotEqualTo(String value) {
            addCriterion("tp_vpic <>", value, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVpicGreaterThan(String value) {
            addCriterion("tp_vpic >", value, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVpicGreaterThanOrEqualTo(String value) {
            addCriterion("tp_vpic >=", value, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVpicLessThan(String value) {
            addCriterion("tp_vpic <", value, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVpicLessThanOrEqualTo(String value) {
            addCriterion("tp_vpic <=", value, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVpicLike(String value) {
            addCriterion("tp_vpic like", value, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVpicNotLike(String value) {
            addCriterion("tp_vpic not like", value, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVpicIn(List<String> values) {
            addCriterion("tp_vpic in", values, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVpicNotIn(List<String> values) {
            addCriterion("tp_vpic not in", values, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVpicBetween(String value1, String value2) {
            addCriterion("tp_vpic between", value1, value2, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVpicNotBetween(String value1, String value2) {
            addCriterion("tp_vpic not between", value1, value2, "tpVpic");
            return (Criteria) this;
        }

        public Criteria andTpVphoneIsNull() {
            addCriterion("tp_vphone is null");
            return (Criteria) this;
        }

        public Criteria andTpVphoneIsNotNull() {
            addCriterion("tp_vphone is not null");
            return (Criteria) this;
        }

        public Criteria andTpVphoneEqualTo(String value) {
            addCriterion("tp_vphone =", value, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpVphoneNotEqualTo(String value) {
            addCriterion("tp_vphone <>", value, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpVphoneGreaterThan(String value) {
            addCriterion("tp_vphone >", value, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpVphoneGreaterThanOrEqualTo(String value) {
            addCriterion("tp_vphone >=", value, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpVphoneLessThan(String value) {
            addCriterion("tp_vphone <", value, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpVphoneLessThanOrEqualTo(String value) {
            addCriterion("tp_vphone <=", value, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpVphoneLike(String value) {
            addCriterion("tp_vphone like", value, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpVphoneNotLike(String value) {
            addCriterion("tp_vphone not like", value, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpVphoneIn(List<String> values) {
            addCriterion("tp_vphone in", values, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpVphoneNotIn(List<String> values) {
            addCriterion("tp_vphone not in", values, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpVphoneBetween(String value1, String value2) {
            addCriterion("tp_vphone between", value1, value2, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpVphoneNotBetween(String value1, String value2) {
            addCriterion("tp_vphone not between", value1, value2, "tpVphone");
            return (Criteria) this;
        }

        public Criteria andTpLevelIsNull() {
            addCriterion("tp_level is null");
            return (Criteria) this;
        }

        public Criteria andTpLevelIsNotNull() {
            addCriterion("tp_level is not null");
            return (Criteria) this;
        }

        public Criteria andTpLevelEqualTo(String value) {
            addCriterion("tp_level =", value, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpLevelNotEqualTo(String value) {
            addCriterion("tp_level <>", value, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpLevelGreaterThan(String value) {
            addCriterion("tp_level >", value, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpLevelGreaterThanOrEqualTo(String value) {
            addCriterion("tp_level >=", value, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpLevelLessThan(String value) {
            addCriterion("tp_level <", value, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpLevelLessThanOrEqualTo(String value) {
            addCriterion("tp_level <=", value, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpLevelLike(String value) {
            addCriterion("tp_level like", value, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpLevelNotLike(String value) {
            addCriterion("tp_level not like", value, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpLevelIn(List<String> values) {
            addCriterion("tp_level in", values, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpLevelNotIn(List<String> values) {
            addCriterion("tp_level not in", values, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpLevelBetween(String value1, String value2) {
            addCriterion("tp_level between", value1, value2, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpLevelNotBetween(String value1, String value2) {
            addCriterion("tp_level not between", value1, value2, "tpLevel");
            return (Criteria) this;
        }

        public Criteria andTpPriceIsNull() {
            addCriterion("tp_price is null");
            return (Criteria) this;
        }

        public Criteria andTpPriceIsNotNull() {
            addCriterion("tp_price is not null");
            return (Criteria) this;
        }

        public Criteria andTpPriceEqualTo(String value) {
            addCriterion("tp_price =", value, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpPriceNotEqualTo(String value) {
            addCriterion("tp_price <>", value, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpPriceGreaterThan(String value) {
            addCriterion("tp_price >", value, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpPriceGreaterThanOrEqualTo(String value) {
            addCriterion("tp_price >=", value, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpPriceLessThan(String value) {
            addCriterion("tp_price <", value, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpPriceLessThanOrEqualTo(String value) {
            addCriterion("tp_price <=", value, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpPriceLike(String value) {
            addCriterion("tp_price like", value, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpPriceNotLike(String value) {
            addCriterion("tp_price not like", value, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpPriceIn(List<String> values) {
            addCriterion("tp_price in", values, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpPriceNotIn(List<String> values) {
            addCriterion("tp_price not in", values, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpPriceBetween(String value1, String value2) {
            addCriterion("tp_price between", value1, value2, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpPriceNotBetween(String value1, String value2) {
            addCriterion("tp_price not between", value1, value2, "tpPrice");
            return (Criteria) this;
        }

        public Criteria andTpLocationIsNull() {
            addCriterion("tp_location is null");
            return (Criteria) this;
        }

        public Criteria andTpLocationIsNotNull() {
            addCriterion("tp_location is not null");
            return (Criteria) this;
        }

        public Criteria andTpLocationEqualTo(String value) {
            addCriterion("tp_location =", value, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpLocationNotEqualTo(String value) {
            addCriterion("tp_location <>", value, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpLocationGreaterThan(String value) {
            addCriterion("tp_location >", value, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpLocationGreaterThanOrEqualTo(String value) {
            addCriterion("tp_location >=", value, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpLocationLessThan(String value) {
            addCriterion("tp_location <", value, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpLocationLessThanOrEqualTo(String value) {
            addCriterion("tp_location <=", value, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpLocationLike(String value) {
            addCriterion("tp_location like", value, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpLocationNotLike(String value) {
            addCriterion("tp_location not like", value, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpLocationIn(List<String> values) {
            addCriterion("tp_location in", values, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpLocationNotIn(List<String> values) {
            addCriterion("tp_location not in", values, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpLocationBetween(String value1, String value2) {
            addCriterion("tp_location between", value1, value2, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpLocationNotBetween(String value1, String value2) {
            addCriterion("tp_location not between", value1, value2, "tpLocation");
            return (Criteria) this;
        }

        public Criteria andTpZipIsNull() {
            addCriterion("tp_zip is null");
            return (Criteria) this;
        }

        public Criteria andTpZipIsNotNull() {
            addCriterion("tp_zip is not null");
            return (Criteria) this;
        }

        public Criteria andTpZipEqualTo(String value) {
            addCriterion("tp_zip =", value, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpZipNotEqualTo(String value) {
            addCriterion("tp_zip <>", value, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpZipGreaterThan(String value) {
            addCriterion("tp_zip >", value, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpZipGreaterThanOrEqualTo(String value) {
            addCriterion("tp_zip >=", value, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpZipLessThan(String value) {
            addCriterion("tp_zip <", value, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpZipLessThanOrEqualTo(String value) {
            addCriterion("tp_zip <=", value, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpZipLike(String value) {
            addCriterion("tp_zip like", value, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpZipNotLike(String value) {
            addCriterion("tp_zip not like", value, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpZipIn(List<String> values) {
            addCriterion("tp_zip in", values, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpZipNotIn(List<String> values) {
            addCriterion("tp_zip not in", values, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpZipBetween(String value1, String value2) {
            addCriterion("tp_zip between", value1, value2, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpZipNotBetween(String value1, String value2) {
            addCriterion("tp_zip not between", value1, value2, "tpZip");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeIsNull() {
            addCriterion("tp_opentime is null");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeIsNotNull() {
            addCriterion("tp_opentime is not null");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeEqualTo(String value) {
            addCriterion("tp_opentime =", value, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeNotEqualTo(String value) {
            addCriterion("tp_opentime <>", value, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeGreaterThan(String value) {
            addCriterion("tp_opentime >", value, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeGreaterThanOrEqualTo(String value) {
            addCriterion("tp_opentime >=", value, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeLessThan(String value) {
            addCriterion("tp_opentime <", value, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeLessThanOrEqualTo(String value) {
            addCriterion("tp_opentime <=", value, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeLike(String value) {
            addCriterion("tp_opentime like", value, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeNotLike(String value) {
            addCriterion("tp_opentime not like", value, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeIn(List<String> values) {
            addCriterion("tp_opentime in", values, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeNotIn(List<String> values) {
            addCriterion("tp_opentime not in", values, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeBetween(String value1, String value2) {
            addCriterion("tp_opentime between", value1, value2, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpOpentimeNotBetween(String value1, String value2) {
            addCriterion("tp_opentime not between", value1, value2, "tpOpentime");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeIsNull() {
            addCriterion("tp_creatTime is null");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeIsNotNull() {
            addCriterion("tp_creatTime is not null");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeEqualTo(Date value) {
            addCriterion("tp_creatTime =", value, "tpCreattime");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeNotEqualTo(Date value) {
            addCriterion("tp_creatTime <>", value, "tpCreattime");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeGreaterThan(Date value) {
            addCriterion("tp_creatTime >", value, "tpCreattime");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tp_creatTime >=", value, "tpCreattime");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeLessThan(Date value) {
            addCriterion("tp_creatTime <", value, "tpCreattime");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeLessThanOrEqualTo(Date value) {
            addCriterion("tp_creatTime <=", value, "tpCreattime");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeIn(List<Date> values) {
            addCriterion("tp_creatTime in", values, "tpCreattime");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeNotIn(List<Date> values) {
            addCriterion("tp_creatTime not in", values, "tpCreattime");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeBetween(Date value1, Date value2) {
            addCriterion("tp_creatTime between", value1, value2, "tpCreattime");
            return (Criteria) this;
        }

        public Criteria andTpCreattimeNotBetween(Date value1, Date value2) {
            addCriterion("tp_creatTime not between", value1, value2, "tpCreattime");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeIsNull() {
            addCriterion("tp_vlongitude is null");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeIsNotNull() {
            addCriterion("tp_vlongitude is not null");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeEqualTo(String value) {
            addCriterion("tp_vlongitude =", value, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeNotEqualTo(String value) {
            addCriterion("tp_vlongitude <>", value, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeGreaterThan(String value) {
            addCriterion("tp_vlongitude >", value, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("tp_vlongitude >=", value, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeLessThan(String value) {
            addCriterion("tp_vlongitude <", value, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeLessThanOrEqualTo(String value) {
            addCriterion("tp_vlongitude <=", value, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeLike(String value) {
            addCriterion("tp_vlongitude like", value, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeNotLike(String value) {
            addCriterion("tp_vlongitude not like", value, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeIn(List<String> values) {
            addCriterion("tp_vlongitude in", values, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeNotIn(List<String> values) {
            addCriterion("tp_vlongitude not in", values, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeBetween(String value1, String value2) {
            addCriterion("tp_vlongitude between", value1, value2, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlongitudeNotBetween(String value1, String value2) {
            addCriterion("tp_vlongitude not between", value1, value2, "tpVlongitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeIsNull() {
            addCriterion("tp_vlatitude is null");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeIsNotNull() {
            addCriterion("tp_vlatitude is not null");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeEqualTo(String value) {
            addCriterion("tp_vlatitude =", value, "tpVlatitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeNotEqualTo(String value) {
            addCriterion("tp_vlatitude <>", value, "tpVlatitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeGreaterThan(String value) {
            addCriterion("tp_vlatitude >", value, "tpVlatitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("tp_vlatitude >=", value, "tpVlatitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeLessThan(String value) {
            addCriterion("tp_vlatitude <", value, "tpVlatitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeLessThanOrEqualTo(String value) {
            addCriterion("tp_vlatitude <=", value, "tpVlatitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeLike(String value) {
            addCriterion("tp_vlatitude like", value, "tpVlatitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeNotLike(String value) {
            addCriterion("tp_vlatitude not like", value, "tpVlatitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeIn(List<String> values) {
            addCriterion("tp_vlatitude in", values, "tpVlatitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeNotIn(List<String> values) {
            addCriterion("tp_vlatitude not in", values, "tpVlatitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeBetween(String value1, String value2) {
            addCriterion("tp_vlatitude between", value1, value2, "tpVlatitude");
            return (Criteria) this;
        }

        public Criteria andTpVlatitudeNotBetween(String value1, String value2) {
            addCriterion("tp_vlatitude not between", value1, value2, "tpVlatitude");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_viewpoint
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_viewpoint
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}